version: "2.0"

services:
  nats:
    build:
      context: "./nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
    restart: always

  api:
    build:
      context: "./api"
    depends_on:
      - nats
      - jaeger
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix: /api"
      - "traefik.port=8789"
      - "traefik.frontend.entryPoints=http"
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      JAEGER_URL: jaeger
      API_PORT: 8789
      API_HOST: 0.0.0.0
      HEMERA_LOG_LEVEL: error

  math-service:
    build:
      context: "./math-service"
    links:
      - nats
    depends_on:
      - nats
      - redis
      - jaeger
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      JAEGER_URL: jaeger
      HEMERA_LOG_LEVEL: error

  cache-service:
    build:
      context: "./cache-service"
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    restart: always
    environment:
      REDIS_PORT: 6379
      REDIS_URL: redis
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      HEMERA_LOG_LEVEL: error

  natsboard:
    build:
      context: "./natsboard"
    depends_on:
      - nats
    links:
      - nats
    ports:
      - "3000:3000"
      - "3001:3001"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "8182:80"
      - "8181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml