version: "2.0"

services:
  nats:
    build:
      context: "./nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server

  api:
    build:
      context: "./api"
    depends_on:
      - nats
      - zipkin
    links:
      - zipkin
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix: /api"
      - "traefik.port=8789"
      - "traefik.frontend.entryPoints=http"
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      ZIPKIN_URL: zipkin
      ZIPKIN_PORT: 9411
      API_PORT: 8789
      API_HOST: 0.0.0.0
      HEMERA_LOG_LEVEL: silent

  math-service:
    build:
      context: "./math-service"
    links:
      - nats
      - zipkin
    depends_on:
      - nats
      - redis
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      ZIPKIN_URL: zipkin
      ZIPKIN_PORT: 9411
      HEMERA_LOG_LEVEL: silent

  cache-service:
    build:
      context: "./cache-service"
    links:
      - nats
      - zipkin
      - redis
    depends_on:
      - nats
      - redis
    restart: always
    environment:
      REDIS_PORT: 6379
      REDIS_URL: redis
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      ZIPKIN_URL: zipkin
      ZIPKIN_PORT: 9411
      HEMERA_LOG_LEVEL: info

  natsboard:
    build:
      context: "./natsboard"
    depends_on:
      - nats
    links:
      - nats
    ports:
      - "3000:3000"
      - "3001:3001"

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    expose:
      - "9411"
    ports:
      # Listen port for the Scribe transport
      - 9410:9410
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    depends_on:
      - zipkin-storage

  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: zipkin-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      # Uncomment to adjust memory used by the dependencies job
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    depends_on:
      - zipkin-storage

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "8182:80"
      - "8181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"